services:
  api:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8082
